### ISSUE TITLE
Integrate basic editor

### ISSUE THREAD

**Issue by YuryDG** [lealceldeiro/org.wcdevs.blog.front#11]
### What is the issue about?

**Integrate an editor.**
Here you are a list of the most used editors.
https://www.kindacode.com/article/popular-open-source-wysiwyg-editors-for-react/

Pay attention to 
**TinyMCE** - https://www.tiny.cloud/docs/demo/full-featured/#
**React Draft Wysiwyg** - https://jpuri.github.io/react-draft-wysiwyg/#/demo

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lealceldeiro** [comment]
@YuryDG , *React Draft Wysiwyg* looks really promising.

Have you taken a decision about which one to use?

**Comment by YuryDG** [comment]
Yes, this one will be the chosen one to start with
