### ISSUE TITLE
[Technical Request] Update README.md

### ISSUE THREAD

**Issue by lealceldeiro** [lealceldeiro/org.wcdevs.blog.front#18]
### What technical change you'd like to see implemented in our project?

The README.md should be enhanced to give a new contributor (or reader) and idea of how to start as quick as possible with the project. Some section that could be added are:

### 1.1 Requirements

Here, there should be a clear description of what needs to be installed in the dev local environment and, how to start the project, how to debug it, and/or any other useful information from a developer perspective.

Motivation for this change:

For example, if I go and execute `yarn dev` I get the following error:

```
/bin/sh: 1: next: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

That's because first I should have executed: `yarn install`. So, such clarifications should be added in the README.md (or any other instruction) file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YuryDG** [comment]
Hi @lealceldeiro, 
I agree with you.
