### ISSUE TITLE
Integrate git-cz to improve commits

### ISSUE THREAD

**Issue by YuryDG** [lealceldeiro/org.wcdevs.blog.front#24]
### Contact Details

yurydgfuentes@gmail.com

### What new feature you'd like to see in our site?

The idea behind this is to standardize git history with a readable message.

Example: 
![image](https://user-images.githubusercontent.com/8725796/156924504-f3e4d342-dec9-4afb-b518-8ca629b4bdbc.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lealceldeiro** [comment]
I had created an initial setup for that. You can check it out here:
https://github.com/lealceldeiro/org.wcdevs.blog.front/blob/main/CONTRIBUTING.md#git-flow

I even added some git hooks (https://github.com/lealceldeiro/org.wcdevs.blog.front/tree/main/scripts/git/hooks) so devs can use them locally to "enforce" it while doing commit/push.

I think this could be a good starting point to enhance it and apply the idea in this ticket.

Any thoughts?

**Comment by YuryDG** [comment]
> I had created an initial setup for that. You can check it out here: https://github.com/lealceldeiro/org.wcdevs.blog.front/blob/main/CONTRIBUTING.md#git-flow
> 
> I even added some git hooks (https://github.com/lealceldeiro/org.wcdevs.blog.front/tree/main/scripts/git/hooks) so devs can use them locally to "enforce" it while doing commit/push.
> 
> I think this could be a good starting point to enhance it and apply the idea in this ticket.
> 
> Any thoughts?

Hi @lealceldeiro,
For commits I was using the integration that VSCODE provides, maybe, for this reason, I missed the hooks you added. 
I'll double-check now but I'm glad you like the PR #25  😄

**Comment by YuryDG** [comment]
I just checked and [ git-cz](https://www.npmjs.com/package/git-cz) has come template we can use to achieve the structure we want. 

I'm going to check how flexible it is in order to discuss it with you in details and we can reconsider update the https://github.com/lealceldeiro/org.wcdevs.blog.front/blob/main/CONTRIBUTING.md#git-flow after we agree

**Comment by lealceldeiro** [comment]
Cool -- whatever we decide as a guideline for commit  messages structure is completely up to us. So, feel free to do whichever enhancements you consider a good fit for the project.

**Comment by lealceldeiro** [comment]
@YuryDG , please triage this ticket in [wcDevs](https://github.com/users/lealceldeiro/projects/3#card-79383431) project appropriately.
